#!/usr/bin/env bash
# script that configures a brand new Ubuntu machine
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "/listen 80 default_server;/ a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx restart

echo "Ceci n'est pas une page" | sudo tee /var/www/html/yas_404.html
sudo sed -i "/listen 80 default_server;/ a error_page 404 /yas_404.html;" /etc/nginx/sites-available/default

sudo sed -i "/http {/ a add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart