#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it.

mysql -u root -P"$1" --all-databaes > backup.sql
tar -zcvf "$(date '+%d-%m-%Y').tar.gz" backup.sql
