#!/usr/bin/env bash
# script that creates file and display diffirent massages when receiving diffirent signals
file=/var/run/myscript.pid
echo $$ >> $file
trap 'echo I hate the kill command; sudo rm $file; exit' SIGTERM
trap 'echo Y U no love me?!' SIGINT
trap 'sudo rm $file; exit' SIGQUIT
i=1
while [ $i -gt 0 ]; do
	echo "To infinity and beyond"
	sleep 2
done
