#!/usr/bin/env bash
# script that gives you information about the school file
num=1
while [ $num -le 100 ]; do
	if [ $((num % 5)) == 0 ] && [ $((num % 3)) == 0 ]; then
		echo "FizzBuzz"
	elif [ $((num % 5)) == 0 ]; then
		echo "Buzz"
	elif [ $((num % 3)) == 0 ]; then
		echo "Fizz"
	else
		echo $num
	fi
	num=$((num + 1))
done
