#!/usr/bin/env bash
# This script is displaying "Best School" 10 times at 4 display bad luck, at 8 display good luck
i=0
while [ $((i++)) -le 9 ]; do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
