#!/usr/bin/env bash
# script that displays numbers from 1 to 20 
hour=0
while [ $hour -lt 13 ]; do
	echo Hour: $hour
	min=1
	while [ $min -lt 60 ]; do
		echo $min
		min=$((min+1))
	done
	hour=$((hour+1))
done
