#!/usr/bin/env bash
# Bash script that configures an Ubuntu server
cp /etc/hosts ~/hosts.new
sudo sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.c/' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
